version: "2"
services:
  planer:
    container_name: planer
    build: .
    ports:
      - "400:80"
    depends_on:
      - "mongo"
    restart: always
  mongo:
    container_name: mongo
    image: nonoroazoro/rpi-mongo
    restart: always
    ports:
        - "401:27014"
    volumes:
      - "/opt/mongodb:/data/db"
#  mongoex:
#    container_name: mongo-express
#    image: ind3x/rpi-mongo-express
#    environment:
#        - ME_CONFIG_OPTIONS_EDITORTHEME=tomorrow-night-bright
#        - ME_CONFIG_MONGODB_SERVER=mongo
#        - ME_CONFIG_MONGODB_PORT=27017
#        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
#    ports:
#        - "402:8081"
#    links:
#        - mongo

