version: "2"
services:
  planer:
    container_name: planer
    build: .
    ports:
      - "80:80"
    depends_on:
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"