version: "2"
services:
  planer:
    container_name: planer
    build: .
    ports:
      - "400:80"
      - "401:443"
    depends_on:
      - "mongo"
    restart: always
  mongo:
    container_name: mongo
    image: nonoroazoro/rpi-mongo
    ports:
      - "27017:27017"
    restart: always
  