version: "2"
services:
  planer:
    container_name: planer
    build: .
    expose:
      - "443"
    labels:
      - "traefik.frontend.rule=Host:planer.localhost"
      - "traefik.frontend.rule=Host:planer.minis-quirin.de"
    depends_on:
      - "mongo"
    restart: always
  mongo:
    container_name: mongo
    image: nonoroazoro/rpi-mongo
    ports:
      - "27017:27017"
    restart: always
  
networks:
  web:
    external: true