version: "2"
services:
  planer:
    container_name: planer
    build: .
    ports:
      - "400:80"
    depends_on:
      - "mongo"
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  mongo:
    container_name: mongo
    image: nonoroazoro/rpi-mongo
    restart: always
    volumes:
      - "/opt/mongodb:/data/db"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  mongoex:
    container_name: mongo-express
    image: ind3x/rpi-mongo-express
    environment:
        - ME_CONFIG_OPTIONS_EDITORTHEME=tomorrow-night-bright
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
        - "402:8081"
    links:
        - mongo
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

